# Essential services for AppFlowy Cloud - SUPER MINIMAL VERSION
# Only the absolutely necessary services to get core functionality working

services:
  postgres:
    restart: on-failure
    image: pgvector/pgvector:pg15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=0c24791672e502b068e0cf682bcc5fb1
      - POSTGRES_INITDB_ARGS=--auth-local=trust --auth-host=md5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    restart: on-failure
    image: redis

  minio:
    restart: on-failure
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  gotrue:
    restart: on-failure
    depends_on:
      - postgres
    image: appflowyinc/gotrue:latest
    environment:
      - GOTRUE_ADMIN_EMAIL=admin@yourdomain.com
      - GOTRUE_ADMIN_PASSWORD=QWeS1EVqzuiV+MZ6MLazkf9le3qwN3H8uIvEd+O09nY=
      - GOTRUE_DISABLE_SIGNUP=false
      - GOTRUE_SITE_URL=appflowy-flutter://
      - GOTRUE_URI_ALLOW_LIST=**
      - GOTRUE_JWT_SECRET=FOc09wLUzG44WjrllGgkoGbT6tQO16OMQ7E8cxRfZ4VdgZjndOdLIH5i7u2w9VDn
      - GOTRUE_JWT_EXP=7200
      - GOTRUE_JWT_ADMIN_GROUP_NAME=supabase_admin
      - GOTRUE_DB_DRIVER=postgres
      - API_EXTERNAL_URL=https://english-appflowy.g9awyq.easypanel.host/gotrue
      - DATABASE_URL=postgres://postgres:0c24791672e502b068e0cf682bcc5fb1@postgres:5432/postgres?search_path=auth
      - PORT=9999
      - GOTRUE_MAILER_AUTOCONFIRM=true
      - GOTRUE_RATE_LIMIT_EMAIL_SENT=100
      - GOTRUE_SMTP_HOST=localhost
      - GOTRUE_SMTP_PORT=587
      - GOTRUE_SMTP_USER=noreply@localhost
      - GOTRUE_SMTP_PASS=password
      - GOTRUE_SMTP_ADMIN_EMAIL=admin@localhost

  appflowy_cloud:
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - RUST_LOG=info
      - APPFLOWY_ENVIRONMENT=production
      - APPFLOWY_DATABASE_URL=postgres://postgres:0c24791672e502b068e0cf682bcc5fb1@postgres:5432/postgres
      - APPFLOWY_REDIS_URI=redis://redis:6379
      - APPFLOWY_GOTRUE_JWT_SECRET=FOc09wLUzG44WjrllGgkoGbT6tQO16OMQ7E8cxRfZ4VdgZjndOdLIH5i7u2w9VDn
      - APPFLOWY_GOTRUE_JWT_EXP=7200
      - APPFLOWY_GOTRUE_BASE_URL=http://gotrue:9999
      - APPFLOWY_S3_CREATE_BUCKET=true
      - APPFLOWY_S3_USE_MINIO=true
      - APPFLOWY_S3_MINIO_URL=http://minio:9000
      - APPFLOWY_S3_ACCESS_KEY=minioadmin
      - APPFLOWY_S3_SECRET_KEY=minioadmin
      - APPFLOWY_S3_BUCKET=appflowy
      - APPFLOWY_S3_REGION=us-east-1
      - APPFLOWY_ACCESS_CONTROL=true
      - APPFLOWY_DATABASE_MAX_CONNECTIONS=40
      - APPFLOWY_BASE_URL=https://english-appflowy.g9awyq.easypanel.host
      - APPFLOWY_WEB_URL=https://english-appflowy.g9awyq.easypanel.host
    image: appflowyinc/appflowy_cloud:latest
    depends_on:
      - gotrue
      - postgres
      - redis

volumes:
  postgres_data:
  minio_data: